### PR TITLE
Fix for fully cancelled tween still firing TweenEnd

### LINKED ISSUE #966: Problem with cancelTween()
I think I found a bug in the Tween component. I'm using the latest nightly.

What happens is:
- I start a tween of say 1 sec.
- I cancel the tween at 0.5sec.
- I start another tween at 0.7sec.
- The first tween isn't fully cancelled! (e.g. still in .tweens array)

It seems the full cancellation happens only after the time the tween would have ended originally. This effect however screws up my game logic since I use tween loops and rely on correct order of these things.

Unfortunately I don't have a small self-contained example, but maybe it is easy to find the bug without it.

### PR DESCRIPTION
**Pull request by mucaho**
Fixes #966 , with solution suggested by airza.
Adds more tests.

### CODE REVIEW

File: src/core/tween.js [hunk 1]
```diff
@@ -156,9 +156,11 @@ module.exports = {
   * Stops tweening the specified group of properties, and fires the "TweenEnd" event.
   */
   _endTween: function(properties){
+    var notEmpty = false;
     for (var propname in properties){
+      notEmpty = true;
       delete this.tweenGroup[propname];
     }
-    this.trigger("TweenEnd", properties);
+    if (notEmpty) this.trigger("TweenEnd", properties);
```
Comment (starwed) [inline src/core/tween.js:164]: 👍  I think this approach is preferable to something like using `object.keys()`, since we're already iterating through the properties.

**Review by starwed — APPROVED** [review]
Looks good, thanks for adding more tests.
