### PR TITLE
Fixing key press detection for Opera

### LINKED ISSUE #400: Fourway controls (WASD + arrow keys) don't work in Opera
Crafty's Fourway (and possibly Twoway, etc.) component doesn't respond to W, A, S, D, or the arrow keys in Opera.

As an example, see the demo (one of the ones linked from craftyjs.com) for Cron: http://blackscorp.github.com/cron/ 

Here's my full system info:

Version 12.12 
Build 1707 
Platform Mac OS X 
System 10.7.5

### PR DESCRIPTION
**Pull request by darrentorpey**
Resolves #400

I based this on how the jQuery Event object works. This should help protect us from similar issues in the future.

If we need to copy more properties from the original event object, add them to the "props" variable.

### CODE REVIEW

**Comment by darrentorpey** [comment]
My goal here was to start with a minimal working set. I'm not sure how much or what kind of future needs we'd like to anticipate.

I gather the input libraries part of Crafty is fledgling so I wasn't sure what needs I could anticipate. Is there a roadmap for more generalized support of control schemes?

**Comment by mpetrovic** [comment]
Everything is fledgling and no, there's no roadmap past the work I want to
do with Workers right now. I put that into the pile of things to work on,
though.

**Comment by darrentorpey** [comment]
We could also set a "originalEvent" property on our custom event. That will allow transparency into the original event for developers. I think this would be helpful in general even as we develop a more robust set of control utilities/components in Crafty.

**Comment by mpetrovic** [comment]
we should definitely do that, but it should be a last resort option for advanced usage

File: src/controls.js [hunk 1]
```diff
@@ -247,7 +247,18 @@ Crafty.extend({
 	* Unicode of the key pressed
 	*/
 	keyboardDispatch: function (e) {
-		e.key = e.keyCode || e.which;
+		// Use a Crafty-standard event object to avoid cross-browser issues
+		var original = e,
+			evnt = {},
+			props = "char charCode keyCode type".split(" ");
+		for (i = props.length; i;) {
+			prop = props[--i];
```
Comment (louisstow) [inline src/controls.js]: this looks like it should be `var`ed else it be global

File: src/controls.js [hunk 2]
```diff
@@ -247,7 +247,18 @@ Crafty.extend({
 	* Unicode of the key pressed
 	*/
 	keyboardDispatch: function (e) {
-		e.key = e.keyCode || e.which;
+		// Use a Crafty-standard event object to avoid cross-browser issues
+		var original = e,
+			evnt = {},
+			props = "char charCode keyCode type".split(" ");
```
Comment (louisstow) [inline src/controls.js]: Other props I would add to this list is `shiftKey`, `ctrlKey`, `metaKey` and `timestamp`. That would probably do for now. Do this and the var thing and I will pull :)

File: src/controls.js (hunk 1 above)
Comment (darrentorpey) [inline src/controls.js]: Ah, cool call; I missed that one.

**Comment by louisstow** [comment]
I also agree with storing the `originalEvent` object on this.

**Comment by louisstow** [comment]
Great, thanks a lot!
