### PR TITLE
Change how rotation cascades for 2D entities

### LINKED ISSUE #593: Rotations don't compose correctly
Rotating an entity, attaching it to a parent, and then rotating the parent doesn't work the way you'd expect.

Currently when the parents rotate, we rotate all children about the same origin.  But this doesn't work if the children are already rotated about their own origins.

I think the correct approach is to manually change the `x` and `y` coordinates of children when the parent rotates, while also rotating them about their own origin.

As reported [by Justin](https://groups.google.com/forum/?fromgroups#!topic/craftyjs/FS1UvM9t_ms) on the google group.  [A fiddle that shows the issue.](http://jsfiddle.net/2VnKw/1/)

### PR DESCRIPTION
**Pull request by starwed**
Previously when a parent rotated, it changed the origin and rotation of children directly.  This prevented independent rotation of children.

After this patch, children are rotated about their own origin, and shifted to the correct position relative to the parent.

This fixes #593.

### CODE REVIEW

**Comment by starwed** [comment]
I'm going to go ahead and merge this.

File: src/2D.js [hunk 1]
```diff
@@ -935,12 +935,12 @@ Crafty.c("2D", {
      * Method for rotation rather than through a setter
      */
     rotate: function (e) {
-        //assume event data origin
-        this._origin.x = e.o.x - this._x;
-        this._origin.y = e.o.y - this._y;
-
-        //modify through the setter method
+        var x2, y2;
+        x2 =  (this._x + this._origin.x - e.o.x) * e.cos + (this._y + this._origin.y - e.o.y) * e.sin + (e.o.x - this._origin.x)
```
Comment (potomak) [inline src/2D.js:939]: I run `grunt check` and I noted you're missing closing `;` at the end of this line.

See #540.
